version: "3.9"

services:
  # ── FastAPI 백엔드 ──────────────────────────
  backend:
    build:
      context: ./back
      dockerfile: Dockerfile
    container_name: fragrance-backend
    ports:
      - "8000:8000"
    restart: unless-stopped

  # ── Streamlit 프론트엔드 ───────────────────
  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile
    container_name: fragrance-frontend
    ports:
      - "8501:8501"
    volumes:
      - ./front:/app
    environment:
      - FASTAPI_HOST= 98.94.222.157
    depends_on:
      - backend
    restart: unless-stopped
